config/routes.rb
PaperclipAndDropboxSample::Application.routes.draw do
  resources :images
  root to: 'images#index'

end

app/models/image.rb
class Image < ActiveRecord::Base
  attr_accessible :title, :picture
  has_attached_file :picture, :styles => { :thumb => "100x100>" },# :default_url => "/images/:style/missing.png"
    :storage => :dropbox,
    :dropbox_credentials => Rails.root.join("config/dropbox.yml"),
    :path => "pictures/:style/:id_:filename"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  def index
    @image = Image.new
    @images = Image.all
  end

  def show
    @image = Image.find(params[:id])
  end

  def create
    @image = Image.create(params[:image])
    redirect_to image_path(@image.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/images/index.html.haml
%h1
  ="Page title"
= form_for @image, :url => images_path, :html => { :multipart => true } do |f|
  = f.label :title
  = f.text_field :title
  = f.file_field :picture
  = f.submit
- @images.each do |img|
  = link_to(image_tag(img.picture.url(:thumb)), image_path(img.id))

app/views/images/show.html.haml
%h1
  = @image.title
= image_tag(@image.picture.url)

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PaperclipAndDropboxSample</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>